apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: manasabreddy/devops-mansa-app:c008b1ff57c860674717654d9d96d5df4a92a73d
        ports:
        - containerPort: 5000
