apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: manasabreddy/devops-mansa-app:60ebe6e156714a0ee001e0d51cbc1b2b950d4bd7
        ports:
        - containerPort: 5000
