apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: manasabreddy/devops-mansa-app:56be77d4cc14020077e21b785bf7558df3561b5b
        ports:
        - containerPort: 5000
