apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: manasabreddy/devops-mansa-app:2c517d9ff156844013020efc678c88b294e59d24
        ports:
        - containerPort: 5000
