apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: manasabreddy/devops-mansa-app:bf8a8bf39f33875df855dd792d5576ebbeb12631
          ports:
            - containerPort: 5000
