name: Promote Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to promote to'
        required: true
        type: choice
        options:
          - staging
          - production

permissions:
  contents: write
  pull-requests: write

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get Latest Image Tag from DEV
        run: |
          IMAGE=$(grep -m1 "image:" k8s/dev/deployment.yaml | sed 's/.*image:[[:space:]]*//')
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "Dev Image: $IMAGE"

      - name: Update Target Environment
        run: |
          sed -i "s|image:.*|image: $IMAGE|" k8s/${{ github.event.inputs.environment }}/deployment.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Promote image to ${{ github.event.inputs.environment }}"
          branch: promote-${{ github.event.inputs.environment }}-${{ github.run_number }}
          base: main
          title: "Promote to ${{ github.event.inputs.environment }}"
          body: |
            Auto promotion from Dev to ${{ github.event.inputs.environment }}

            Image: ${{ env.IMAGE }}
          add-paths: |
            k8s/${{ github.event.inputs.environment }}/deployment.yaml
